export const CARS_LIST_REQUEST = "CARS_LIST_REQUEST";
export const CARS_LIST_SUCCESS = "CARS_LIST_SUCCESS";
export const CARS_LIST_FAIL = "CARS_LIST_FAIL";
export const CARS_LIST_RESET = "CARS_LIST_RESET";

export const CARS_CREATE_REQUEST = "CARS_CREATE_REQUEST";
export const CARS_CREATE_SUCCESS = "CARS_CREATE_SUCCESS";
export const CARS_CREATE_FAIL = "CARS_CREATE_FAIL";
export const CARS_CREATE_RESET = "CARS_CREATE_RESET";

export const CARS_DETAILS_REQUEST = "CARS_DETAILS_REQUEST";
export const CARS_DETAILS_SUCCESS = "CARS_DETAILS_SUCCESS";
export const CARS_DETAILS_FAIL = "CARS_DETAILS_FAIL";
export const CARS_DETAILS_RESET = "CARS_DETAILS_RESET";

export const CAR_EDIT_REQUEST = "CAR_EDIT_REQUEST";
export const CAR_EDIT_SUCCESS = "CAR_EDIT_SUCCESS";
export const CAR_EDIT_FAIL = "CAR_EDIT_FAIL";
export const CAR_EDIT_RESET = "CAR_EDIT_RESET";

export const CARS_CREATE_UPLOAD_IMAGE_REQUEST =
  "CARS_CREATE_UPLOAD_IMAGE_REQUEST";
export const CARS_CREATE_UPLOAD_IMAGE_SUCCESS =
  "CARS_CREATE_UPLOAD_IMAGE_SUCCESS";
export const CARS_CREATE_UPLOAD_IMAGE_FAIL = "CARS_CREATE_UPLOAD_IMAGE_FAIL";
export const CARS_CREATE_UPLOAD_IMAGE_RESET = "CARS_CREATE_UPLOAD_IMAGE_RESET";

export const CARS_EDIT_UPLOAD_IMAGE_REQUEST = "CARS_EDIT_UPLOAD_IMAGE_REQUEST";
export const CARS_EDIT_UPLOAD_IMAGE_SUCCESS = "CARS_EDIT_UPLOAD_IMAGE_SUCCESS";
export const CARS_EDIT_UPLOAD_IMAGE_FAIL = "CARS_EDIT_UPLOAD_IMAGE_FAIL";
export const CARS_EDIT_UPLOAD_IMAGE_RESET = "CARS_EDIT_UPLOAD_IMAGE_RESET";

export const CAR_LIST_BY_LOCATION_REQUEST = "CAR_LIST_BY_LOCATION_REQUEST";
export const CAR_LIST_BY_LOCATION_SUCCESS = "CAR_LIST_BY_LOCATION_SUCCESS";
export const CAR_LIST_BY_LOCATION_FAIL = "CAR_LIST_BY_LOCATION_FAIL";
export const CAR_LIST_BY_LOCATION_RESET = "CAR_LIST_BY_LOCATION_RESET";

export const CAR_RESERVATION_REQUEST = "CAR_RESERVATION_REQUEST";
export const CAR_RESERVATION_SUCCESS = "CAR_RESERVATION_SUCCESS";
export const CAR_RESERVATION_FAIL = "CAR_RESERVATION_FAIL";
export const CAR_RESERVATION_RESET = "CAR_RESERVATION_RESET";

export const CAR_LIST_RESERVATION_REQUEST = "CAR_LIST_RESERVATION_REQUEST";
export const CAR_LIST_RESERVATION_SUCCESS = "CAR_LIST_RESERVATION_SUCCESS";
export const CAR_LIST_RESERVATION_FAIL = "CAR_LIST_RESERVATION_FAIL";
export const CAR_LIST_RESERVATION_RESET = "CAR_LIST_RESERVATION_RESET";

export const CAR_RESERVATION_DELETE_REQUEST = "CAR_RESERVATION_DELETE_REQUEST";
export const CAR_RESERVATION_DELETE_SUCCESS = "CAR_RESERVATION_DELETE_SUCCESS";
export const CAR_RESERVATION_DELETE_FAIL = "CAR_RESERVATION_DELETE_FAIL";

export const CAR_SINGLE_RESERVATION_REQUEST = "CAR_SINGLE_RESERVATION_REQUEST";
export const CAR_SINGLE_RESERVATION_SUCCESS = "CAR_SINGLE_RESERVATION_SUCCESS";
export const CAR_SINGLE_RESERVATION_FAIL = "CAR_SINGLE_RESERVATION_FAIL";
export const CAR_SINGLE_RESERVATION_RESET = "CAR_SINGLE_RESERVATION_RESET";

export const CAR_SINGLE_EDIT_RESERVATION_REQUEST =
  "CAR_SINGLE_EDIT_RESERVATION_REQUEST";
export const CAR_SINGLE_EDIT_RESERVATION_SUCCESS =
  "CAR_SINGLE_EDIT_RESERVATION_SUCCESS";
export const CAR_SINGLE_EDIT_RESERVATION_FAIL =
  "CAR_SINGLE_EDIT_RESERVATION_FAIL";
export const CAR_SINGLE_EDIT_RESERVATION_RESET =
  "CAR_SINGLE_EDIT_RESERVATION_RESET";

export const CAR_RENT_CREATE_REQUEST = "CAR_RENT_CREATE_REQUEST";
export const CAR_RENT_CREATE_SUCCESS = "CAR_RENT_CREATE_SUCCESS";
export const CAR_RENT_CREATE_FAIL = "CAR_RENT_CREATE_FAIL";
export const CAR_RENT_CREATE_RESET = "CAR_RENT_CREATE_RESET";

export const CAR_LIST_RENTS_REQUEST = "CAR_LIST_RENTS_REQUEST";
export const CAR_LIST_RENTS_SUCCESS = "CAR_LIST_RENTS_SUCCESS";
export const CAR_LIST_RENTS_FAIL = "CAR_LIST_RENTS_FAIL";
export const CAR_LIST_RENTS_RESET = "CAR_LIST_RENTS_RESET";

export const CAR_RENT_DETAILS_REQUEST = "CAR_RENT_DETAILS_REQUEST";
export const CAR_RENT_DETAILS_SUCCESS = "CAR_RENT_DETAILS_SUCCESS";
export const CAR_RENT_DETAILS_FAIL = "CAR_RENT_DETAILS_FAIL";
export const CAR_RENT_DETAILS_RESET = "CAR_RENT_DETAILS_RESET";

export const CAR_RENT_UPDATE_REQUEST = "CAR_RENT_UPDATE_REQUEST";
export const CAR_RENT_UPDATE_SUCCESS = "CAR_RENT_UPDATE_SUCCESS";
export const CAR_RENT_UPDATE_FAIL = "CAR_RENT_UPDATE_FAIL";
export const CAR_RENT_UPDATE_RESET = "CAR_RENT_UPDATE_RESET";

export const CAR_RENT_EDIT_REQUEST = "CAR_RENT_EDIT_REQUEST";
export const CAR_RENT_EDIT_SUCCESS = "CAR_RENT_EDIT_SUCCESS";
export const CAR_RENT_EDIT_FAIL = "CAR_RENT_EDIT_FAIL";
export const CAR_RENT_EDIT_RESET = "CAR_RENT_EDIT_RESET";

export const SEARCH_RESERVATIONS_REQUEST = "SEARCH_RESERVATIONS_REQUEST";
export const SEARCH_RESERVATIONS_SUCCESS = "SEARCH_RESERVATIONS_SUCCESS";
export const SEARCH_RESERVATIONS_FAIL = "SEARCH_RESERVATIONS_FAIL";
export const SEARCH_RESERVATIONS_RESET = "SEARCH_RESERVATIONS_RESET";

export const FILTER_RESERVATIONS_REQUEST = "FILTER_RESERVATIONS_REQUEST";
export const FILTER_RESERVATIONS_SUCCESS = "FILTER_RESERVATIONS_SUCCESS";
export const FILTER_RESERVATIONS_FAIL = "FILTER_RESERVATIONS_FAIL";
export const FILTER_RESERVATIONS_RESET = "FILTER_RESERVATIONS_RESET";
