export const LOCATION_LIST_REQUEST = "LOCATION_LIST_REQUEST";
export const LOCATION_LIST_SUCCESS = "LOCATION_LIST_SUCCESS";
export const LOCATION_LIST_FAIL = "LOCATION_LIST_FAIL";
export const LOCATION_LIST_RESET = "LOCATION_LIST_RESET";

export const LOCATION_CREATE_REQUEST = "LOCATION_CREATE_REQUEST";
export const LOCATION_CREATE_SUCCESS = "LOCATION_CREATE_SUCCESS";
export const LOCATION_CREATE_FAIL = "LOCATION_CREATE_FAIL";
export const LOCATION_CREATE_RESET = "LOCATION_CREATE_RESET";

export const LOCATION_EDIT_REQUEST = "LOCATION_EDIT_REQUEST";
export const LOCATION_EDIT_SUCCESS = "LOCATION_EDIT_SUCCESS";
export const LOCATION_EDIT_FAIL = "LOCATION_EDIT_FAIL";
export const LOCATION_EDIT_RESET = "LOCATION_EDIT_RESET";

export const LOCATION_DETAILS_REQUEST = "LOCATION_DETAILS_REQUEST";
export const LOCATION_DETAILS_SUCCESS = "LOCATION_DETAILS_SUCCESS";
export const LOCATION_DETAILS_FAIL = "LOCATION_DETAILS_FAIL";
export const LOCATION_DETAILS_RESET = "LOCATION_DETAILS_RESET";

export const LOCATION_EDIT_UPLOAD_IMAGE_REQUEST =
  "LOCATION_EDIT_UPLOAD_IMAGE_REQUEST";
export const LOCATION_EDIT_UPLOAD_IMAGE_SUCCESS =
  "LOCATION_EDIT_UPLOAD_IMAGE_SUCCESS";
export const LOCATION_EDIT_UPLOAD_IMAGE_FAIL =
  "LOCATION_EDIT_UPLOAD_IMAGE_FAIL";
export const LOCATION_EDIT_UPLOAD_IMAGE_RESET =
  "LOCATION_EDIT_UPLOAD_IMAGE_RESET";

export const LOCATION_CREATE_UPLOAD_IMAGE_REQUEST =
  "LOCATION_CREATE_UPLOAD_IMAGE_REQUEST";
export const LOCATION_CREATE_UPLOAD_IMAGE_SUCCESS =
  "LOCATION_CREATE_UPLOAD_IMAGE_SUCCESS";
export const LOCATION_CREATE_UPLOAD_IMAGE_FAIL =
  "LOCATION_CREATE_UPLOAD_IMAGE_FAIL";
export const LOCATION_CREATE_UPLOAD_IMAGE_RESET =
  "LOCATION_CREATE_UPLOAD_IMAGE_RESET";
