# Generated by Django 4.0.1 on 2022-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_cars_main_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='locations',
        ),
        migrations.AddField(
            model_name='cars',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='to_the_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
