# Generated by Django 4.0.1 on 2022-01-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_cars_locations_cars_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='main_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='core_app.locations'),
        ),
    ]
