# Generated by Django 4.0.1 on 2022-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_cars_main_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_ARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('code_registration', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator_ARC', models.CharField(max_length=255)),
                ('on_the_way', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_the_location', models.CharField(blank=True, max_length=255, null=True)),
                ('come_back', models.BooleanField(default=False)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
