# Generated by Django 4.0.1 on 2022-01-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_cars_arc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars_arc',
            name='code_registration',
            field=models.CharField(max_length=20),
        ),
    ]
