# Generated by Django 4.0.1 on 2022-01-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_alter_cars_arc_code_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars_arc',
            name='date_of_entry',
        ),
        migrations.RemoveField(
            model_name='cars_arc',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cars_arc',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cars_arc',
            name='id_car',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars_arc',
            name='id_location',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
