# Generated by Django 4.0.1 on 2022-01-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_remove_cars_arc_date_of_entry_remove_cars_arc_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('client_document_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_from', models.DateField()),
                ('hour_from', models.CharField(max_length=10)),
                ('date_to', models.DateField()),
                ('hour_to', models.CharField(max_length=10)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=255)),
                ('id_cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carReservations', to='core_app.cars')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationReservations', to='core_app.locations')),
            ],
        ),
    ]
