# Generated by Django 4.0.1 on 2022-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_remove_cars_reservation_hour_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars_reservation',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars_reservation',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
