# Generated by Django 4.0.1 on 2022-01-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_cars_reservation_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars_reservation',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars_reservation',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
