# Generated by Django 4.0.1 on 2022-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_alter_cars_reservation_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_reservation',
            name='creator_change',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cars_reservation',
            name='date_of_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cars_reservation',
            name='id_arc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cars_reservation',
            name='typ_change',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
