# Generated by Django 4.0.1 on 2022-02-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_cars_reservation_creator_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars_reservation',
            old_name='typ_change',
            new_name='type_change',
        ),
    ]
