# Generated by Django 4.0.1 on 2022-02-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_alter_locations_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_Rents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('client_document_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('deposit', models.CharField(max_length=255)),
                ('deposit_currency', models.CharField(max_length=255)),
                ('deposit_is_active', models.BooleanField(default=False)),
                ('total_price', models.CharField(max_length=255)),
                ('total_price_currency', models.CharField(max_length=255)),
                ('total_price_is_paid', models.BooleanField(default=False)),
                ('creator', models.CharField(max_length=255)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carRents', to='core_app.cars')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationRents', to='core_app.locations')),
            ],
        ),
    ]
