# Generated by Django 4.0.1 on 2022-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_cars_rents'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_rents',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
