# Generated by Django 4.0.1 on 2022-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_cars_rents_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_reservation',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
