# Generated by Django 4.0.1 on 2022-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0021_cars_reservation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='supp_unique_var',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
